[Window]
	autohide.class."Hyprland" = true
	autohide.class."albert" = true
	autohide.class."main.py" = true
	autohide.class."ulauncher" = true

	autohide.title."Albert" = true

	rename.class."code" = "vscode"
	rename.class."vesktop" = "discord"
	[Window.ignore]
		class."kitty-dropterm" = true
		class."albert" = true
		class."main.py" = true
		class."ulauncher" = true
	[Window.translate]
		# Enable this, if you want to manually give each Application a Title
		#force-manual = true
		class."None" = "Hyprland"
		class."brave-browser" = "Brave"
		class."org.gnome.Nautilus" = "Finder"
		class."org.gnome.NautilusPreviewer" = "Finder"
		class."org.gnome.Software" = "App Store"
		class."discord" = "Discord"
		class."vesktop" = "Vesktop"

[Widgets]
	dock.enable = true
	panel.enable = true

[Notch]
	[Notch.style]

[Dock]
	[Dock.style]
		exclusive = false
		autohide = true
		mode = "center" # center, full
		height = 64
		icon-size = 32
		position = "bottom" # left, right, bottom
	[Dock.pinned]
		"org.gnome.Nautilus" = "nautilus"
		"org.gnome.Settings" = "XDG_CURRENT_DESKTOP=GNOME gnome-control-center"
		"org.gnome.Software" = "gnome-software"
		"gnome-disks" = "gnome-disks"
		"org.gnome.baobab" = "baobab"
		"kitty" = "kitty"
		"brave-browser" = "brave"
		"code" = "code"
		"org.gnome.Calculator" = "gnome-calculator"
		"org.gnome.TextEditor" = "gnome-text-editor"
		"org.gnome.Loupe" = "loupe"
		"org.gnome.clocks" = "gnome-clocks"
		"krita" = "krita"
		"spotify" = "spotify"
		"vesktop" = "vesktop"
		"org.keepassxc.KeePassXC" = "keepassxc"
		"com.github.rafostar.Clapper" = "clapper"
		"blender" = "blender"
		"obsidian" = "obsidian"
[Corners]
	[Corners.style]
[Panel]
	[Panel.style]
		height = 24
		full = true
		margin = [0, 0, 0, 0]
		rounding = "0"
		date-format = "%a %b %d %H:%M"
		icon = ""

[Workspace]
ignore.id.9 = true

[Shell]
	[Shell.about]
		window.width = 250
		window.height = 355
		window.resizable = false
		computer-label = "Env Shell"
		computer-caption = "ESH 0.1.0, 2024"
		more-info = "https://github.com/E3nviction/envshell"
	[Shell.env-menu]
		options.settings.on-click = "code ~/.config/"
		options.store.label = "Nix Store..."
		options.store.on-click = "xdg-open https://search.nixos.org/packages"

[Icons]
directory = "/run/current-system/sw/share/icons/WhiteSur-dark/apps/scalable/"

[Bluetooth]
show-hidden-devices = false