[Window]
	autohide.class."main.py" = true
	[Window.ignore]
		class."main.py" = true
	[Window.translate]
		smart-title = true
		class."None" = "Hyprland"
[Widgets]
	dock.enable = true
	panel.enable = true
[Dock]
	title.limit = 25
	exclusive = false
	lazy-time = 1000
	autohide = true
	mode = "center"
	size = 1
	position = "bottom"
	debug = false
	[Dock.pinned]
		"org.gnome.Nautilus" = "nautilus"
		"kitty" = "kitty"
[Panel]
	height = 24
	full = true
	mode = "normal"
	date-format = "%a %b %d %H:%M"
	icon = ""

[Workspace]
ignore.id.9 = true

[Shell]
	[Shell.about]
		window.width = 250
		window.height = 355
		window.resizable = false
		computer-label = "Env Shell"
		computer-caption = "ESH 0.1.0, 2024"
		more-info = "https://github.com/E3nviction/envshell"
	[Shell.env-menu]
		options.settings.on-click = "code ~/.config/"
		options.store.label = "Nix Store..."
		options.store.on-click = "xdg-open https://search.nixos.org/packages"

[Cache]
directory = "envshell"

[Bluetooth]
show-hidden-devices = false